# Generated by Django 3.1.5 on 2021-02-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_invoice_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date']},
        ),
    ]
