# Generated by Django 3.1.5 on 2023-02-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_auto_20210213_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
